baseURL = "http://yang-wei.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true

author = "Yang Wei"
copyright = "[Home](/) &#183; Theme [Simpleness](https://github.com/RainerChiang/simpleness) Powered by [Hugo](https://gohugo.io/)"

theme = "simpleness"
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  showmonth = true
  slogan = "always make it happen"
  description = "A simple blog."
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  enableHeaderVisitor = true
  debug = true

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/yang-wei"
  twitter = "https://twitter.com/yangwei21"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
